//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HardwareInventoryService.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public int UserID { get; set; }
        public string ItemName { get; set; }
        public double Price { get; set; }
        public Nullable<System.DateTime> DateOfPurchase { get; set; }
        public string Shop { get; set; }
        public Nullable<int> Warranty { get; set; }
        public int CategoryID { get; set; }
        public string Note { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual Users Users { get; set; }
    }
}
